name = "turningcat"
main = "src/index.js"
compatibility_date = "2024-04-01"

# 静态资源目录
assets = { directory = "./assets", binding = "ASSETS" }

# KV 绑定（保留原有）
[[kv_namespaces]]
binding = "MEDIA_GROUP_CAPTIONS"
id = "24275521efdc464494a2868cd5493888"

[[kv_namespaces]]
binding = "BOT_SETTINGS"
id = "c954edf092794c788b550cb343f93f98"
